/**
 * Calendar Export (ICS format)
 *
 * Export training plans to iCalendar (.ics) format compatible with:
 * - Apple Calendar
 * - Google Calendar
 * - Microsoft Outlook
 * - Any iCal-compatible calendar app
 */

import { createEvents, type EventAttributes, DateArray } from 'ics';
import { format } from 'date-fns';

export interface TrainingPlanExport {
  name: string;
  description?: string;
  goal?: string;
  weeks: Array<{
    weekNumber: number;
    startDate: Date;
    workouts: Array<{
      id: string;
      date: Date;
      type: string;
      name: string;
      duration: number;
      description: string;
      structure?: any;
    }>;
  }>;
}

/**
 * Convert Date to ICS date array format [year, month, day, hour, minute]
 */
function dateToArray(date: Date): DateArray {
  return [
    date.getFullYear(),
    date.getMonth() + 1, // ICS months are 1-indexed
    date.getDate(),
    date.getHours(),
    date.getMinutes(),
  ];
}

/**
 * Generate workout description for calendar event
 */
function generateWorkoutDescription(workout: {
  type: string;
  duration: number;
  description: string;
  structure?: any;
}): string {
  let desc = `Type: ${workout.type}\n`;
  desc += `Duration: ${workout.duration} minutes\n\n`;
  desc += `${workout.description}\n\n`;

  if (workout.structure) {
    desc += `Structure:\n`;
    if (Array.isArray(workout.structure.intervals)) {
      workout.structure.intervals.forEach((interval: any, idx: number) => {
        desc += `  ${idx + 1}. ${interval.description || interval.type} - ${interval.duration}min\n`;
      });
    }
  }

  desc += `\n⚡ Generated by Garmin AI Coach Pro`;

  return desc;
}

/**
 * Get workout color/category based on type
 */
function getWorkoutCategory(type: string): string {
  const categories: Record<string, string> = {
    INTERVAL: 'High Intensity',
    TEMPO: 'Moderate Intensity',
    LONG: 'Endurance',
    EASY: 'Easy Recovery',
    RECOVERY: 'Recovery',
    RACE: 'Race Day',
    STRENGTH: 'Strength Training',
  };

  return categories[type] || 'Workout';
}

/**
 * Export training plan to ICS calendar format
 */
export function exportPlanToICS(plan: TrainingPlanExport): string | Error {
  try {
    const events: EventAttributes[] = [];

    // Add each workout as a calendar event
    for (const week of plan.weeks) {
      for (const workout of week.workouts) {
        const startDate = new Date(workout.date);

        // Set default time to 6:00 AM if no time specified
        if (startDate.getHours() === 0 && startDate.getMinutes() === 0) {
          startDate.setHours(6, 0, 0, 0);
        }

        const endDate = new Date(startDate.getTime() + workout.duration * 60 * 1000);

        const event: EventAttributes = {
          uid: `workout-${workout.id}@garmin-ai-coach-pro.com`,
          start: dateToArray(startDate),
          end: dateToArray(endDate),
          title: workout.name,
          description: generateWorkoutDescription(workout),
          location: '',
          categories: [getWorkoutCategory(workout.type)],
          status: 'CONFIRMED',
          busyStatus: 'BUSY',
          organizer: {
            name: 'Garmin AI Coach Pro',
            email: 'noreply@garmin-ai-coach-pro.com',
          },
          alarms: [
            {
              action: 'display',
              description: `${workout.name} starts in 1 hour`,
              trigger: { hours: 1, minutes: 0, before: true },
            },
          ],
        };

        events.push(event);
      }
    }

    // Create ICS file content
    const { error, value } = createEvents(events);

    if (error) {
      return new Error(`Failed to create ICS file: ${error}`);
    }

    if (!value) {
      return new Error('No ICS content generated');
    }

    return value;
  } catch (error: any) {
    return new Error(`Export failed: ${error.message}`);
  }
}

/**
 * Export single workout to ICS
 */
export function exportWorkoutToICS(workout: {
  id: string;
  date: Date;
  type: string;
  name: string;
  duration: number;
  description: string;
  structure?: any;
}): string | Error {
  try {
    const startDate = new Date(workout.date);

    // Set default time to 6:00 AM if no time specified
    if (startDate.getHours() === 0 && startDate.getMinutes() === 0) {
      startDate.setHours(6, 0, 0, 0);
    }

    const endDate = new Date(startDate.getTime() + workout.duration * 60 * 1000);

    const event: EventAttributes = {
      uid: `workout-${workout.id}@garmin-ai-coach-pro.com`,
      start: dateToArray(startDate),
      end: dateToArray(endDate),
      title: workout.name,
      description: generateWorkoutDescription(workout),
      categories: [getWorkoutCategory(workout.type)],
      status: 'CONFIRMED',
      busyStatus: 'BUSY',
      organizer: {
        name: 'Garmin AI Coach Pro',
        email: 'noreply@garmin-ai-coach-pro.com',
      },
      alarms: [
        {
          action: 'display',
          description: `${workout.name} starts in 1 hour`,
          trigger: { hours: 1, minutes: 0, before: true },
        },
      ],
    };

    const { error, value } = createEvents([event]);

    if (error) {
      return new Error(`Failed to create ICS file: ${error}`);
    }

    if (!value) {
      return new Error('No ICS content generated');
    }

    return value;
  } catch (error: any) {
    return new Error(`Export failed: ${error.message}`);
  }
}

/**
 * Generate filename for ICS download
 */
export function generateICSFilename(planName: string): string {
  const sanitized = planName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  const timestamp = format(new Date(), 'yyyy-MM-dd');

  return `${sanitized}-${timestamp}.ics`;
}
